### ISSUE TITLE
Make color label for tooltip 

### ISSUE THREAD

**Issue by zamkevich** [estorski/langlay#107]
It can be colored tooltip will be more suitable method than the inscription.
What if automatically generate different colors tips for each of the following languages?

And one more idea: turn off the second and every next tooltip in one window without switching focus.

**Comment by zamkevich** [comment]
> You mean, just draw a colored box with no text inside?

Yes, because they are difficult to distinguish between:

![image](https://user-images.githubusercontent.com/13717428/43993968-7cbd6fd2-9dd8-11e8-800d-58b91176fb06.png)

_Я имею ввиду, что сейчас их сложно отличить: чёрный тултип, три буквы — нужно вчитываться. Можно выхватить системные языки и рандомно назначить им цвета тултипов, но запоминать выбранный цвет, чтобы пользователь привык._
_Или дать возможность выбрать цвет тултипа для каждого языка системного языка/раскладки, но для этого придётся допиливать UI, а он у вас и так уже со скроллом. Пора делать вкладки :-)_

**Comment by estorski** [comment]
OK, I've implemented the "smart focus" feature for a tooltip. 👍 

The colored tooltip background is on its way.

**Comment by estorski** [comment]
This one should be finally resolved with `v2.1`
