### ISSUE TITLE
Please add LeftCtrl+LeftAlt key sequence

### ISSUE THREAD

**Issue by Ygarr** [estorski/langlay#113]
Pleasee add LeftCtrl+LeftAlt combination to switch on of layouts

**Comment by estorski** [comment]
Hey @Ygarr 

You can do it on your own using the Settings interface:
<img width="231" alt="Langlay_2020-11-13_13-06-52" src="https://user-images.githubusercontent.com/9264460/99066164-2c716480-25b1-11eb-968e-121f08b33cb8.png">

Worked for me.
