### ISSUE TITLE
Add some ways to change overlay position in settings UI

### ISSUE THREAD

**Issue by ir0kez** [estorski/langlay#32]
My proposal is to add another section in settings UI and provide user with 9 radio-buttons drawn on some kind of monitor picture.
Like this:
/------------------\
|-o------o------o-|
|-o------o------o-|
|-o------o------o-|
\\------------------/

**Comment by DmitryKolesnichenko** [comment]
Would be nice to have an overlay size slider as well. The max size could be limited by screen size (it's ridiculous tho, but can find its usages). Just my two cents.
