### ISSUE TITLE
Two icons in the tray

### ISSUE THREAD

**Issue by DariaPovilyay** [estorski/langlay#43]
1.Opened the application.
2.Opened Settings via tray icon.
3.Changed setting "run at windows startup".
4.Applied the changes.
5.Closed Settings.
6.Get two icons in the tray.
Worked with Windows 7 (64bit).

**Comment by ir0kez** [comment]
My guess is that the main app (tray) is closed incorrectly (forced termination) for some reason.

**Comment by ir0kez** [comment]
Would be nice if u mention the OS u work with, to make the process of bug fixing smoother.
